import type {
  ChatUser,
  Conversation,
  ConversationGroup,
  Message,
} from "./types";

export const CURRENT_USER_ID = "user-me";

export const CHAT_USERS: ChatUser[] = [
  {
    id: CURRENT_USER_ID,
    name: "Saber Alipour",
    username: "saber",
    email: "alipournet@gmail.com",
    role: "Product Engineer",
    avatarColor: "bg-violet-500/15 text-violet-600 dark:text-violet-300",
    initials: "SA",
    status: "online",
  },
  {
    id: "user-amelia",
    name: "Amelia Reyes",
    username: "amelia",
    email: "amelia@acme.io",
    role: "Design Lead",
    avatarColor: "bg-rose-500/15 text-rose-600 dark:text-rose-300",
    initials: "AR",
    status: "online",
  },
  {
    id: "user-jonas",
    name: "Jonas Becker",
    username: "jonas",
    email: "jonas@acme.io",
    role: "Engineering Manager",
    avatarColor: "bg-sky-500/15 text-sky-600 dark:text-sky-300",
    initials: "JB",
    status: "away",
  },
  {
    id: "user-mira",
    name: "Mira Khan",
    username: "mira",
    email: "mira@acme.io",
    role: "Frontend Engineer",
    avatarColor: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-300",
    initials: "MK",
    status: "online",
  },
  {
    id: "user-luca",
    name: "Luca Romano",
    username: "luca",
    email: "luca@acme.io",
    role: "Backend Engineer",
    avatarColor: "bg-amber-500/15 text-amber-700 dark:text-amber-300",
    initials: "LR",
    status: "busy",
  },
  {
    id: "user-priya",
    name: "Priya Shah",
    username: "priya",
    email: "priya@acme.io",
    role: "PM",
    avatarColor: "bg-fuchsia-500/15 text-fuchsia-600 dark:text-fuchsia-300",
    initials: "PS",
    status: "offline",
  },
  {
    id: "user-noor",
    name: "Noor Hassan",
    username: "noor",
    email: "noor@northstar.co",
    role: "Northstar Client",
    avatarColor: "bg-cyan-500/15 text-cyan-700 dark:text-cyan-300",
    initials: "NH",
    status: "online",
  },
  {
    id: "user-david",
    name: "David Chen",
    username: "david",
    email: "david@orbital.dev",
    role: "Orbital Client",
    avatarColor: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-300",
    initials: "DC",
    status: "away",
  },
  {
    id: "user-sofia",
    name: "Sofia Martinez",
    username: "sofia",
    email: "sofia@orbital.dev",
    role: "Marketing",
    avatarColor: "bg-pink-500/15 text-pink-600 dark:text-pink-300",
    initials: "SM",
    status: "offline",
  },
  {
    id: "user-bot",
    name: "Shadex Bot",
    username: "system",
    email: "system@shadex.app",
    role: "System",
    avatarColor: "bg-muted text-muted-foreground",
    initials: "SX",
    status: "online",
  },
];

export const CHAT_GROUPS: ConversationGroup[] = [
  { id: "favorites", name: "Favorites", icon: "favorites" },
  { id: "direct", name: "Direct Messages", icon: "direct" },
  { id: "teams", name: "Teams", icon: "teams" },
  { id: "clients", name: "Clients", icon: "clients" },
  { id: "projects", name: "Projects", icon: "projects" },
  { id: "archived", name: "Archived", icon: "archived" },
];

const now = new Date();
const minutes = (n: number) => new Date(now.getTime() - n * 60 * 1000);
const hours = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000);
const days = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);

export const CHAT_CONVERSATIONS: Conversation[] = [
  {
    id: "c-amelia",
    kind: "direct",
    name: "Amelia Reyes",
    participantIds: [CURRENT_USER_ID, "user-amelia"],
    groupId: "favorites",
    pinned: true,
    muted: false,
    archived: false,
    unreadCount: 2,
    lastReadAt: minutes(35),
    createdAt: days(30),
    updatedAt: minutes(2),
  },
  {
    id: "c-design",
    kind: "group",
    name: "Design Crit",
    description: "Weekly design review channel",
    participantIds: [
      CURRENT_USER_ID,
      "user-amelia",
      "user-jonas",
      "user-mira",
      "user-priya",
    ],
    groupId: "favorites",
    pinned: true,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: minutes(8),
    createdAt: days(45),
    updatedAt: minutes(12),
  },
  {
    id: "c-jonas",
    kind: "direct",
    name: "Jonas Becker",
    participantIds: [CURRENT_USER_ID, "user-jonas"],
    groupId: "direct",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: hours(1),
    createdAt: days(20),
    updatedAt: hours(1),
  },
  {
    id: "c-mira",
    kind: "direct",
    name: "Mira Khan",
    participantIds: [CURRENT_USER_ID, "user-mira"],
    groupId: "direct",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 4,
    lastReadAt: hours(3),
    createdAt: days(14),
    updatedAt: minutes(22),
  },
  {
    id: "c-luca",
    kind: "direct",
    name: "Luca Romano",
    participantIds: [CURRENT_USER_ID, "user-luca"],
    groupId: "direct",
    pinned: false,
    muted: true,
    archived: false,
    unreadCount: 0,
    lastReadAt: hours(8),
    createdAt: days(10),
    updatedAt: hours(5),
  },
  {
    id: "c-priya",
    kind: "direct",
    name: "Priya Shah",
    participantIds: [CURRENT_USER_ID, "user-priya"],
    groupId: "direct",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: days(1),
    createdAt: days(8),
    updatedAt: days(1),
  },
  {
    id: "c-frontend",
    kind: "group",
    name: "Frontend Guild",
    description: "Shared notes, RFCs and pairing requests",
    participantIds: [
      CURRENT_USER_ID,
      "user-mira",
      "user-luca",
      "user-amelia",
      "user-jonas",
    ],
    groupId: "teams",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 1,
    lastReadAt: hours(2),
    createdAt: days(60),
    updatedAt: hours(2),
  },
  {
    id: "c-leadership",
    kind: "group",
    name: "Leadership",
    description: "Quarterly planning & ops",
    participantIds: [CURRENT_USER_ID, "user-jonas", "user-priya"],
    groupId: "teams",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: days(2),
    createdAt: days(90),
    updatedAt: days(2),
  },
  {
    id: "c-northstar",
    kind: "direct",
    name: "Noor Hassan",
    description: "Northstar account",
    participantIds: [CURRENT_USER_ID, "user-noor"],
    groupId: "clients",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 3,
    lastReadAt: hours(6),
    createdAt: days(120),
    updatedAt: minutes(45),
  },
  {
    id: "c-orbital",
    kind: "group",
    name: "Orbital · Launch",
    description: "Cross-team launch coordination",
    participantIds: [
      CURRENT_USER_ID,
      "user-david",
      "user-sofia",
      "user-priya",
      "user-amelia",
    ],
    groupId: "clients",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: hours(4),
    createdAt: days(75),
    updatedAt: hours(4),
  },
  {
    id: "c-billing",
    kind: "group",
    name: "Billing Revamp",
    description: "Stripe migration & pricing changes",
    participantIds: [
      CURRENT_USER_ID,
      "user-luca",
      "user-jonas",
      "user-priya",
    ],
    groupId: "projects",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: days(1),
    createdAt: days(50),
    updatedAt: hours(20),
  },
  {
    id: "c-mobile",
    kind: "group",
    name: "Mobile v2",
    description: "iOS & Android refresh",
    participantIds: [
      CURRENT_USER_ID,
      "user-mira",
      "user-luca",
      "user-amelia",
    ],
    groupId: "projects",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: days(3),
    createdAt: days(40),
    updatedAt: days(3),
  },
  {
    id: "c-legacy",
    kind: "group",
    name: "Legacy Migration",
    description: "Phase 1 wrap-up",
    participantIds: [CURRENT_USER_ID, "user-jonas", "user-luca"],
    groupId: "archived",
    pinned: false,
    muted: true,
    archived: true,
    unreadCount: 0,
    lastReadAt: days(40),
    createdAt: days(200),
    updatedAt: days(35),
  },
];

const mid = (() => {
  let i = 0;
  return () => `m-${++i}`;
})();

export const CHAT_MESSAGES: Message[] = [
  // c-amelia (active conversation)
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "text",
    content: "Hey! Did you get a chance to look at the dashboard mocks?",
    status: "read",
    createdAt: hours(5),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: CURRENT_USER_ID,
    type: "text",
    content:
      "Yes — going through them now. The empty states look really clean. Have you decided on the chart palette yet?",
    status: "read",
    createdAt: hours(4),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "text",
    content:
      "Mostly. I want to keep the muted set so the data reads clearly. Will share a final swatch in the morning.",
    status: "read",
    createdAt: hours(4),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "image",
    content: "Preview attached.",
    attachments: [
      {
        id: "att-1",
        name: "dashboard-overview.png",
        size: 1_840_000,
        mimeType: "image/png",
        kind: "image",
        previewColor: "from-rose-200 via-fuchsia-200 to-violet-200",
      },
    ],
    status: "read",
    createdAt: hours(3),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: CURRENT_USER_ID,
    type: "text",
    content:
      "This is great. I think we can ship the v1 with this layout — Jonas already approved the cards section.",
    status: "read",
    createdAt: hours(2),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "text",
    content:
      "Perfect. I'll prep the handoff doc tonight and tag Mira so she can wire up the responsive states.",
    replyTo: {
      messageId: "m-5",
      authorId: CURRENT_USER_ID,
      authorName: "Saber Alipour",
      preview:
        "This is great. I think we can ship the v1 with this layout — Jonas already approved the cards section.",
      type: "text",
    },
    status: "read",
    createdAt: hours(2),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "file",
    content: "Specs for the new chart components.",
    attachments: [
      {
        id: "att-2",
        name: "chart-specs-v2.pdf",
        size: 3_240_000,
        mimeType: "application/pdf",
        kind: "file",
      },
    ],
    status: "read",
    createdAt: minutes(40),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "text",
    content: "Let me know if anything looks off — happy to revise tomorrow.",
    status: "delivered",
    createdAt: minutes(2),
  },

  // c-design
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-bot",
    type: "system",
    content: "Mira Khan joined the conversation.",
    status: "read",
    createdAt: hours(20),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-jonas",
    type: "text",
    content:
      "Quick reminder: Friday review at 3pm. Drop your decks in the thread by EOD Thursday.",
    status: "read",
    createdAt: hours(18),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-mira",
    type: "text",
    content: "On it. I'll cover the new data grid filters.",
    status: "read",
    createdAt: hours(17),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-amelia",
    type: "text",
    content: "I'll bring the audit for the marketing site refresh.",
    status: "read",
    createdAt: hours(12),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: CURRENT_USER_ID,
    type: "text",
    content:
      "I'll demo the chat module — should be ready by Thursday morning.",
    status: "read",
    createdAt: minutes(20),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-priya",
    type: "text",
    content: "Love that. Will block the room and send calendar holds.",
    status: "delivered",
    createdAt: minutes(12),
  },

  // c-jonas
  {
    id: mid(),
    conversationId: "c-jonas",
    authorId: "user-jonas",
    type: "text",
    content: "Quick sync at 4? Want to align on Q3 priorities.",
    status: "read",
    createdAt: hours(3),
  },
  {
    id: mid(),
    conversationId: "c-jonas",
    authorId: CURRENT_USER_ID,
    type: "text",
    content: "Works for me — I'll prep a short list before then.",
    status: "read",
    createdAt: hours(2),
  },
  {
    id: mid(),
    conversationId: "c-jonas",
    authorId: "user-jonas",
    type: "text",
    content: "Thanks!",
    status: "read",
    createdAt: hours(1),
  },

  // c-mira
  {
    id: mid(),
    conversationId: "c-mira",
    authorId: "user-mira",
    type: "text",
    content: "Have a sec to look at the data grid filter bug?",
    status: "read",
    createdAt: hours(4),
  },
  {
    id: mid(),
    conversationId: "c-mira",
    authorId: "user-mira",
    type: "text",
    content:
      "It only repros when you have two active filters AND the toolbar is collapsed.",
    status: "delivered",
    createdAt: hours(4),
  },
  {
    id: mid(),
    conversationId: "c-mira",
    authorId: "user-mira",
    type: "file",
    content: "Captured a quick screen recording.",
    attachments: [
      {
        id: "att-3",
        name: "grid-filter-bug.mov",
        size: 8_120_000,
        mimeType: "video/quicktime",
        kind: "file",
      },
    ],
    status: "delivered",
    createdAt: hours(2),
  },
  {
    id: mid(),
    conversationId: "c-mira",
    authorId: "user-mira",
    type: "text",
    content: "Ping me when you're free — happy to pair on it.",
    status: "delivered",
    createdAt: minutes(22),
  },

  // c-luca
  {
    id: mid(),
    conversationId: "c-luca",
    authorId: "user-luca",
    type: "text",
    content:
      "Deploy is green. Watching error rates for the next 30 minutes just in case.",
    status: "read",
    createdAt: hours(6),
  },
  {
    id: mid(),
    conversationId: "c-luca",
    authorId: CURRENT_USER_ID,
    type: "text",
    content: "Nice. Let me know if you need a second pair of eyes.",
    status: "read",
    createdAt: hours(5),
  },

  // c-priya
  {
    id: mid(),
    conversationId: "c-priya",
    authorId: "user-priya",
    type: "text",
    content: "Roadmap sync notes are in the doc — added owners next to each item.",
    status: "read",
    createdAt: days(1),
  },

  // c-frontend
  {
    id: mid(),
    conversationId: "c-frontend",
    authorId: "user-mira",
    type: "text",
    content:
      "I drafted an RFC for moving our data fetching layer onto the new useAPI hook everywhere.",
    status: "read",
    createdAt: hours(8),
  },
  {
    id: mid(),
    conversationId: "c-frontend",
    authorId: "user-luca",
    type: "text",
    content: "Big +1. Will review tonight.",
    status: "read",
    createdAt: hours(7),
  },
  {
    id: mid(),
    conversationId: "c-frontend",
    authorId: "user-amelia",
    type: "text",
    content: "Anything you need from design while you're in there?",
    status: "delivered",
    createdAt: hours(2),
  },

  // c-leadership
  {
    id: mid(),
    conversationId: "c-leadership",
    authorId: "user-jonas",
    type: "text",
    content:
      "Q3 OKRs are locked. Sharing the deck in the channel — please review before Monday.",
    status: "read",
    createdAt: days(2),
  },

  // c-northstar
  {
    id: mid(),
    conversationId: "c-northstar",
    authorId: "user-noor",
    type: "text",
    content:
      "Hi Saber — circling back on the integration. Any updates from your side?",
    status: "read",
    createdAt: hours(8),
  },
  {
    id: mid(),
    conversationId: "c-northstar",
    authorId: CURRENT_USER_ID,
    type: "text",
    content:
      "Hi Noor — yes, we shipped the staging endpoint. I'll send credentials shortly.",
    status: "read",
    createdAt: hours(7),
  },
  {
    id: mid(),
    conversationId: "c-northstar",
    authorId: "user-noor",
    type: "text",
    content: "Perfect, thanks. Will have our team test it by tomorrow.",
    status: "delivered",
    createdAt: minutes(45),
  },

  // c-orbital
  {
    id: mid(),
    conversationId: "c-orbital",
    authorId: "user-bot",
    type: "system",
    content: "Sofia Martinez was added to the conversation.",
    status: "read",
    createdAt: days(3),
  },
  {
    id: mid(),
    conversationId: "c-orbital",
    authorId: "user-david",
    type: "text",
    content: "Launch comms draft is ready for review.",
    status: "read",
    createdAt: hours(6),
  },
  {
    id: mid(),
    conversationId: "c-orbital",
    authorId: "user-sofia",
    type: "text",
    content:
      "I'll polish the copy this afternoon and send it back with track changes.",
    status: "read",
    createdAt: hours(4),
  },

  // c-billing
  {
    id: mid(),
    conversationId: "c-billing",
    authorId: "user-luca",
    type: "text",
    content:
      "Migration script ran clean against the staging snapshot. Ready for the prod dry-run on Wednesday.",
    status: "read",
    createdAt: hours(20),
  },

  // c-mobile
  {
    id: mid(),
    conversationId: "c-mobile",
    authorId: "user-mira",
    type: "text",
    content:
      "Pushed the new navigation prototype to TestFlight — feedback welcome.",
    status: "read",
    createdAt: days(3),
  },

  // c-legacy (archived)
  {
    id: mid(),
    conversationId: "c-legacy",
    authorId: "user-bot",
    type: "system",
    content: "Conversation archived.",
    status: "read",
    createdAt: days(35),
  },
];

CHAT_CONVERSATIONS.forEach((c) => {
  const last = [...CHAT_MESSAGES]
    .filter((m) => m.conversationId === c.id)
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())[0];
  c.lastMessageId = last?.id;
});
