import type {
  ChatUser,
  Conversation,
  ConversationGroup,
  Message,
} from "./types";

export const CURRENT_USER_ID = "user-me";

export const CHAT_USERS: ChatUser[] = [
  {
    id: CURRENT_USER_ID,
    name: "صابر علی‌پور",
    username: "saber",
    email: "alipournet@gmail.com",
    role: "مهندس محصول",
    avatarColor: "bg-violet-500/15 text-violet-600 dark:text-violet-300",
    initials: "صع",
    status: "online",
  },
  {
    id: "user-amelia",
    name: "آملیا ریز",
    username: "amelia",
    email: "amelia@acme.io",
    role: "سرپرست طراحی",
    avatarColor: "bg-rose-500/15 text-rose-600 dark:text-rose-300",
    initials: "آر",
    status: "online",
  },
  {
    id: "user-jonas",
    name: "یوناس بکر",
    username: "jonas",
    email: "jonas@acme.io",
    role: "مدیر مهندسی",
    avatarColor: "bg-sky-500/15 text-sky-600 dark:text-sky-300",
    initials: "یب",
    status: "away",
  },
  {
    id: "user-mira",
    name: "میرا خان",
    username: "mira",
    email: "mira@acme.io",
    role: "مهندس فرانت‌اند",
    avatarColor: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-300",
    initials: "مخ",
    status: "online",
  },
  {
    id: "user-luca",
    name: "لوکا رومانو",
    username: "luca",
    email: "luca@acme.io",
    role: "مهندس بک‌اند",
    avatarColor: "bg-amber-500/15 text-amber-700 dark:text-amber-300",
    initials: "لر",
    status: "busy",
  },
  {
    id: "user-priya",
    name: "پریا شاه",
    username: "priya",
    email: "priya@acme.io",
    role: "مدیر محصول",
    avatarColor: "bg-fuchsia-500/15 text-fuchsia-600 dark:text-fuchsia-300",
    initials: "پش",
    status: "offline",
  },
  {
    id: "user-noor",
    name: "نور حسن",
    username: "noor",
    email: "noor@northstar.co",
    role: "مشتری نورث‌استار",
    avatarColor: "bg-cyan-500/15 text-cyan-700 dark:text-cyan-300",
    initials: "نح",
    status: "online",
  },
  {
    id: "user-david",
    name: "دیوید چن",
    username: "david",
    email: "david@orbital.dev",
    role: "مشتری اوربیتال",
    avatarColor: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-300",
    initials: "دچ",
    status: "away",
  },
  {
    id: "user-sofia",
    name: "سوفیا مارتینز",
    username: "sofia",
    email: "sofia@orbital.dev",
    role: "بازاریابی",
    avatarColor: "bg-pink-500/15 text-pink-600 dark:text-pink-300",
    initials: "سم",
    status: "offline",
  },
  {
    id: "user-bot",
    name: "ربات شادکس",
    username: "system",
    email: "system@shadex.app",
    role: "سیستم",
    avatarColor: "bg-muted text-muted-foreground",
    initials: "رش",
    status: "online",
  },
];

export const CHAT_GROUPS: ConversationGroup[] = [
  { id: "favorites", name: "علاقه‌مندی‌ها", icon: "favorites" },
  { id: "direct", name: "پیام‌های مستقیم", icon: "direct" },
  { id: "teams", name: "تیم‌ها", icon: "teams" },
  { id: "clients", name: "مشتری‌ها", icon: "clients" },
  { id: "projects", name: "پروژه‌ها", icon: "projects" },
  { id: "archived", name: "آرشیو شده", icon: "archived" },
];

const now = new Date();
const minutes = (n: number) => new Date(now.getTime() - n * 60 * 1000);
const hours = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000);
const days = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);

export const CHAT_CONVERSATIONS: Conversation[] = [
  {
    id: "c-amelia",
    kind: "direct",
    name: "آملیا ریز",
    participantIds: [CURRENT_USER_ID, "user-amelia"],
    groupId: "favorites",
    pinned: true,
    muted: false,
    archived: false,
    unreadCount: 2,
    lastReadAt: minutes(35),
    createdAt: days(30),
    updatedAt: minutes(2),
  },
  {
    id: "c-design",
    kind: "group",
    name: "نقد طراحی",
    description: "کانال بررسی هفتگی طراحی",
    participantIds: [
      CURRENT_USER_ID,
      "user-amelia",
      "user-jonas",
      "user-mira",
      "user-priya",
    ],
    groupId: "favorites",
    pinned: true,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: minutes(8),
    createdAt: days(45),
    updatedAt: minutes(12),
  },
  {
    id: "c-jonas",
    kind: "direct",
    name: "یوناس بکر",
    participantIds: [CURRENT_USER_ID, "user-jonas"],
    groupId: "direct",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: hours(1),
    createdAt: days(20),
    updatedAt: hours(1),
  },
  {
    id: "c-mira",
    kind: "direct",
    name: "میرا خان",
    participantIds: [CURRENT_USER_ID, "user-mira"],
    groupId: "direct",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 4,
    lastReadAt: hours(3),
    createdAt: days(14),
    updatedAt: minutes(22),
  },
  {
    id: "c-luca",
    kind: "direct",
    name: "لوکا رومانو",
    participantIds: [CURRENT_USER_ID, "user-luca"],
    groupId: "direct",
    pinned: false,
    muted: true,
    archived: false,
    unreadCount: 0,
    lastReadAt: hours(8),
    createdAt: days(10),
    updatedAt: hours(5),
  },
  {
    id: "c-priya",
    kind: "direct",
    name: "پریا شاه",
    participantIds: [CURRENT_USER_ID, "user-priya"],
    groupId: "direct",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: days(1),
    createdAt: days(8),
    updatedAt: days(1),
  },
  {
    id: "c-frontend",
    kind: "group",
    name: "انجمن فرانت‌اند",
    description: "یادداشت‌ها، RFCها و درخواست‌های هم‌برنامه‌نویسی",
    participantIds: [
      CURRENT_USER_ID,
      "user-mira",
      "user-luca",
      "user-amelia",
      "user-jonas",
    ],
    groupId: "teams",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 1,
    lastReadAt: hours(2),
    createdAt: days(60),
    updatedAt: hours(2),
  },
  {
    id: "c-leadership",
    kind: "group",
    name: "رهبری",
    description: "برنامه‌ریزی و عملیات فصلی",
    participantIds: [CURRENT_USER_ID, "user-jonas", "user-priya"],
    groupId: "teams",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: days(2),
    createdAt: days(90),
    updatedAt: days(2),
  },
  {
    id: "c-northstar",
    kind: "direct",
    name: "نور حسن",
    description: "حساب نورث‌استار",
    participantIds: [CURRENT_USER_ID, "user-noor"],
    groupId: "clients",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 3,
    lastReadAt: hours(6),
    createdAt: days(120),
    updatedAt: minutes(45),
  },
  {
    id: "c-orbital",
    kind: "group",
    name: "اوربیتال · راه‌اندازی",
    description: "هماهنگی راه‌اندازی بین تیم‌ها",
    participantIds: [
      CURRENT_USER_ID,
      "user-david",
      "user-sofia",
      "user-priya",
      "user-amelia",
    ],
    groupId: "clients",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: hours(4),
    createdAt: days(75),
    updatedAt: hours(4),
  },
  {
    id: "c-billing",
    kind: "group",
    name: "بازنگری صورت‌حساب",
    description: "مهاجرت به Stripe و تغییرات قیمت‌گذاری",
    participantIds: [CURRENT_USER_ID, "user-luca", "user-jonas", "user-priya"],
    groupId: "projects",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: days(1),
    createdAt: days(50),
    updatedAt: hours(20),
  },
  {
    id: "c-mobile",
    kind: "group",
    name: "موبایل نسخه ۲",
    description: "بازنگری iOS و اندروید",
    participantIds: [CURRENT_USER_ID, "user-mira", "user-luca", "user-amelia"],
    groupId: "projects",
    pinned: false,
    muted: false,
    archived: false,
    unreadCount: 0,
    lastReadAt: days(3),
    createdAt: days(40),
    updatedAt: days(3),
  },
  {
    id: "c-legacy",
    kind: "group",
    name: "مهاجرت سیستم قدیمی",
    description: "جمع‌بندی فاز ۱",
    participantIds: [CURRENT_USER_ID, "user-jonas", "user-luca"],
    groupId: "archived",
    pinned: false,
    muted: true,
    archived: true,
    unreadCount: 0,
    lastReadAt: days(40),
    createdAt: days(200),
    updatedAt: days(35),
  },
];

const mid = (() => {
  let i = 0;
  return () => `m-${++i}`;
})();

export const CHAT_MESSAGES: Message[] = [
  // c-amelia (active conversation)
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "text",
    content: "سلام! فرصت کردی نگاهی به ماک‌های داشبورد بندازی؟",
    status: "read",
    createdAt: hours(5),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: CURRENT_USER_ID,
    type: "text",
    content:
      "بله — همین حالا دارم بررسی می‌کنم. حالت‌های خالی واقعاً تمیز به نظر می‌رسند. در مورد پالت رنگ نمودارها به نتیجه رسیدی؟",
    status: "read",
    createdAt: hours(4),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "text",
    content:
      "تقریباً. می‌خواهم رنگ‌های ملایم را نگه دارم تا داده‌ها واضح‌تر خوانده شوند. نمونه نهایی را صبح می‌فرستم.",
    status: "read",
    createdAt: hours(4),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "image",
    content: "پیش‌نمایش پیوست شد.",
    attachments: [
      {
        id: "att-1",
        name: "dashboard-overview.png",
        size: 1_840_000,
        mimeType: "image/png",
        kind: "image",
        previewColor: "from-rose-200 via-fuchsia-200 to-violet-200",
      },
    ],
    status: "read",
    createdAt: hours(3),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: CURRENT_USER_ID,
    type: "text",
    content:
      "عالیه. فکر می‌کنم می‌توانیم نسخه اول را با همین چیدمان منتشر کنیم — یوناس بخش کارت‌ها را تأیید کرده است.",
    status: "read",
    createdAt: hours(2),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "text",
    content:
      "عالی. امشب سند تحویل را آماده می‌کنم و میرا را تگ می‌کنم تا حالت‌های واکنش‌گرا را پیاده کند.",
    replyTo: {
      messageId: "m-5",
      authorId: CURRENT_USER_ID,
      authorName: "صابر علی‌پور",
      preview:
        "عالیه. فکر می‌کنم می‌توانیم نسخه اول را با همین چیدمان منتشر کنیم — یوناس بخش کارت‌ها را تأیید کرده است.",
      type: "text",
    },
    status: "read",
    createdAt: hours(2),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "file",
    content: "مشخصات کامپوننت‌های جدید نمودار.",
    attachments: [
      {
        id: "att-2",
        name: "chart-specs-v2.pdf",
        size: 3_240_000,
        mimeType: "application/pdf",
        kind: "file",
      },
    ],
    status: "read",
    createdAt: minutes(40),
  },
  {
    id: mid(),
    conversationId: "c-amelia",
    authorId: "user-amelia",
    type: "text",
    content: "اگر چیزی غیرعادی دیدی بگو — فردا با کمال میل اصلاح می‌کنم.",
    status: "delivered",
    createdAt: minutes(2),
  },

  // c-design
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-bot",
    type: "system",
    content: "میرا خان به گفتگو پیوست.",
    status: "read",
    createdAt: hours(20),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-jonas",
    type: "text",
    content:
      "یادآوری سریع: بررسی روز جمعه ساعت ۳ بعدازظهر. تا پایان روز پنج‌شنبه ارائه‌هایتان را در تاپیک بگذارید.",
    status: "read",
    createdAt: hours(18),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-mira",
    type: "text",
    content: "روی آن کار می‌کنم. فیلترهای جدید جدول داده را پوشش می‌دهم.",
    status: "read",
    createdAt: hours(17),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-amelia",
    type: "text",
    content: "من ممیزی بازنگری سایت بازاریابی را می‌آورم.",
    status: "read",
    createdAt: hours(12),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: CURRENT_USER_ID,
    type: "text",
    content: "من ماژول چت را نمایش می‌دهم — تا صبح پنج‌شنبه آماده می‌شود.",
    status: "read",
    createdAt: minutes(20),
  },
  {
    id: mid(),
    conversationId: "c-design",
    authorId: "user-priya",
    type: "text",
    content: "عالیه. اتاق را رزرو می‌کنم و دعوت تقویم را می‌فرستم.",
    status: "delivered",
    createdAt: minutes(12),
  },

  // c-jonas
  {
    id: mid(),
    conversationId: "c-jonas",
    authorId: "user-jonas",
    type: "text",
    content:
      "ساعت ۴ یک هماهنگی سریع داریم؟ می‌خواهم اولویت‌های سه‌ماهه سوم را هم‌راستا کنیم.",
    status: "read",
    createdAt: hours(3),
  },
  {
    id: mid(),
    conversationId: "c-jonas",
    authorId: CURRENT_USER_ID,
    type: "text",
    content: "برای من مناسبه — قبل از آن یک فهرست کوتاه آماده می‌کنم.",
    status: "read",
    createdAt: hours(2),
  },
  {
    id: mid(),
    conversationId: "c-jonas",
    authorId: "user-jonas",
    type: "text",
    content: "ممنون!",
    status: "read",
    createdAt: hours(1),
  },

  // c-mira
  {
    id: mid(),
    conversationId: "c-mira",
    authorId: "user-mira",
    type: "text",
    content: "وقت داری به باگ فیلتر جدول داده نگاه کنی؟",
    status: "read",
    createdAt: hours(4),
  },
  {
    id: mid(),
    conversationId: "c-mira",
    authorId: "user-mira",
    type: "text",
    content:
      "فقط زمانی تکرار می‌شود که دو فیلتر فعال داشته باشی و نوار ابزار جمع شده باشد.",
    status: "delivered",
    createdAt: hours(4),
  },
  {
    id: mid(),
    conversationId: "c-mira",
    authorId: "user-mira",
    type: "file",
    content: "یک ضبط سریع از صفحه گرفتم.",
    attachments: [
      {
        id: "att-3",
        name: "grid-filter-bug.mov",
        size: 8_120_000,
        mimeType: "video/quicktime",
        kind: "file",
      },
    ],
    status: "delivered",
    createdAt: hours(2),
  },
  {
    id: mid(),
    conversationId: "c-mira",
    authorId: "user-mira",
    type: "text",
    content: "هر وقت آزاد بودی پیام بده — با کمال میل با هم کار می‌کنیم.",
    status: "delivered",
    createdAt: minutes(22),
  },

  // c-luca
  {
    id: mid(),
    conversationId: "c-luca",
    authorId: "user-luca",
    type: "text",
    content:
      "استقرار موفقیت‌آمیز بود. محض احتیاط ۳۰ دقیقه آینده نرخ خطا را زیر نظر می‌گیرم.",
    status: "read",
    createdAt: hours(6),
  },
  {
    id: mid(),
    conversationId: "c-luca",
    authorId: CURRENT_USER_ID,
    type: "text",
    content: "عالیه. اگر به نگاه دوم نیاز داشتی خبر بده.",
    status: "read",
    createdAt: hours(5),
  },

  // c-priya
  {
    id: mid(),
    conversationId: "c-priya",
    authorId: "user-priya",
    type: "text",
    content:
      "یادداشت‌های هماهنگی نقشه‌راه در سند است — کنار هر مورد مسئول آن را اضافه کردم.",
    status: "read",
    createdAt: days(1),
  },

  // c-frontend
  {
    id: mid(),
    conversationId: "c-frontend",
    authorId: "user-mira",
    type: "text",
    content:
      "یک RFC نوشتم برای انتقال لایه دریافت داده ما به هوک جدید useAPI در همه جا.",
    status: "read",
    createdAt: hours(8),
  },
  {
    id: mid(),
    conversationId: "c-frontend",
    authorId: "user-luca",
    type: "text",
    content: "موافقم. امشب بررسی می‌کنم.",
    status: "read",
    createdAt: hours(7),
  },
  {
    id: mid(),
    conversationId: "c-frontend",
    authorId: "user-amelia",
    type: "text",
    content: "از طراحی چیزی لازم داری در این مسیر؟",
    status: "delivered",
    createdAt: hours(2),
  },

  // c-leadership
  {
    id: mid(),
    conversationId: "c-leadership",
    authorId: "user-jonas",
    type: "text",
    content:
      "اهداف فصلی سه‌ماهه سوم نهایی شد. ارائه را در کانال می‌گذارم — لطفاً قبل از دوشنبه بررسی کنید.",
    status: "read",
    createdAt: days(2),
  },

  // c-northstar
  {
    id: mid(),
    conversationId: "c-northstar",
    authorId: "user-noor",
    type: "text",
    content:
      "سلام صابر — درباره یکپارچه‌سازی پیگیری می‌کنم. از سمت شما خبر جدیدی هست؟",
    status: "read",
    createdAt: hours(8),
  },
  {
    id: mid(),
    conversationId: "c-northstar",
    authorId: CURRENT_USER_ID,
    type: "text",
    content:
      "سلام نور — بله، نقطه پایانی استیجینگ را منتشر کردیم. به‌زودی اطلاعات ورود را می‌فرستم.",
    status: "read",
    createdAt: hours(7),
  },
  {
    id: mid(),
    conversationId: "c-northstar",
    authorId: "user-noor",
    type: "text",
    content: "عالی، ممنون. تیم ما تا فردا آن را تست خواهد کرد.",
    status: "delivered",
    createdAt: minutes(45),
  },

  // c-orbital
  {
    id: mid(),
    conversationId: "c-orbital",
    authorId: "user-bot",
    type: "system",
    content: "سوفیا مارتینز به گفتگو اضافه شد.",
    status: "read",
    createdAt: days(3),
  },
  {
    id: mid(),
    conversationId: "c-orbital",
    authorId: "user-david",
    type: "text",
    content: "پیش‌نویس اطلاع‌رسانی راه‌اندازی برای بررسی آماده است.",
    status: "read",
    createdAt: hours(6),
  },
  {
    id: mid(),
    conversationId: "c-orbital",
    authorId: "user-sofia",
    type: "text",
    content: "بعدازظهر متن را صیقل می‌دهم و با تغییرات قابل پیگیری برمی‌گردانم.",
    status: "read",
    createdAt: hours(4),
  },

  // c-billing
  {
    id: mid(),
    conversationId: "c-billing",
    authorId: "user-luca",
    type: "text",
    content:
      "اسکریپت مهاجرت روی اسنپ‌شات استیجینگ بدون خطا اجرا شد. آماده اجرای آزمایشی روی محیط عملیاتی در روز چهارشنبه است.",
    status: "read",
    createdAt: hours(20),
  },

  // c-mobile
  {
    id: mid(),
    conversationId: "c-mobile",
    authorId: "user-mira",
    type: "text",
    content:
      "نمونه اولیه ناوبری جدید را روی TestFlight منتشر کردم — نظرات شما را می‌پذیرم.",
    status: "read",
    createdAt: days(3),
  },

  // c-legacy (archived)
  {
    id: mid(),
    conversationId: "c-legacy",
    authorId: "user-bot",
    type: "system",
    content: "گفتگو آرشیو شد.",
    status: "read",
    createdAt: days(35),
  },
];

CHAT_CONVERSATIONS.forEach((c) => {
  const last = [...CHAT_MESSAGES]
    .filter((m) => m.conversationId === c.id)
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())[0];
  c.lastMessageId = last?.id;
});
