import type { Metadata } from "next";
import { Geist_Mono, Inter, Vazirmatn } from "next/font/google";
import "@/styles/globals.css";
import { QueryClientProvider } from "@/shared/providers/QueryClientProvider";
import { ThemeProvider } from "next-themes";
import { appConfig } from "@/core/config";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const vazirmatn = Vazirmatn({ variable: "--font-vazirmatn", subsets: ["arabic"] });
const geistMono = Geist_Mono({ variable: "--font-mono", subsets: ["latin"] });

const activeFont = appConfig.direction === "rtl" ? vazirmatn : inter;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang={appConfig.locale}
      dir={appConfig.direction}
      className={`${activeFont.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className="min-h-full flex flex-col"
        style={{ fontFamily: activeFont.style.fontFamily }}
      >
        <QueryClientProvider>
          <ThemeProvider attribute="class" defaultTheme="light" disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
